#!/usr/bin/env python3
"""Smoke-test: insert dummy rows into emails_raw / email_stories,
then query and print the result."""

import os
import sys
import uuid
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Allow importing ``app`` when running from services/worker/
# ---------------------------------------------------------------------------
sys.path.insert(0, os.path.realpath(os.path.join(os.path.dirname(__file__), "..")))

# Optional .env support
try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

from sqlalchemy import select
from app.db import get_session
from app.models import EmailRaw, EmailStory

def main() -> None:
    Session = get_session()

    with Session() as session:
        # ---- Insert a dummy raw email --------------------------------
        raw = EmailRaw(
            source="imap:eclipso",
            mailbox="INBOX",
            message_id=f"<test-{uuid.uuid4()}@example.com>",
            from_addr="alice@example.com",
            subject="Test email from db_check.py",
            date_sent=datetime.now(timezone.utc),
            date_received=datetime.now(timezone.utc),
            body_text="Hello, this is a smoke-test email.",
            raw_headers={"X-Test": "true"},
        )
        session.add(raw)
        session.flush()  # populate raw.id

        # ---- Insert a dummy story ------------------------------------
        story = EmailStory(
            email_id=raw.id,
            story_index=0,
            headline="Test headline from db_check.py",
            summary="This is a smoke-test story generated by db_check.py.",
            tags=["test", "smoke"],
            processor="ollama",
            model="llama3.2:3b",
            prompt_version="stories-v1",
            status="ok",
            tokens_in=42,
            tokens_out=18,
            latency_ms=123,
        )
        session.add(story)
        session.commit()

        # ---- Query back the latest story -----------------------------
        stmt = (
            select(EmailRaw, EmailStory)
            .join(EmailStory, EmailRaw.id == EmailStory.email_id)
            .order_by(EmailStory.processed_at.desc())
            .limit(1)
        )
        row = session.execute(stmt).first()

        if row is None:
            print("ERROR: no rows returned after insert!", file=sys.stderr)
            sys.exit(1)

        email, story = row
        print("=" * 60)
        print("db_check.py – verification result")
        print("=" * 60)
        print(f"  Subject:       {email.subject}")
        print(f"  From:          {email.from_addr}")
        print(f"  Date received: {email.date_received}")
        print(f"  Headline:      {story.headline}")
        print(f"  Summary:       {story.summary}")
        print("=" * 60)
        print("SUCCESS ✓")


if __name__ == "__main__":
    main()
